######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 4 07:52:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += babalgui.h winbabel.h wincontact.h
FORMS += babalgui.ui winbabel.ui wincontact.ui
SOURCES += babalgui.cpp main.cpp winbabel.cpp wincontact.cpp
