######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 4 14:40:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += babalgui.h winbabel.h
FORMS += babalgui.ui winbabel.ui
SOURCES += babalgui.cpp main.cpp winbabel.cpp
