######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 3 00:47:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += babelgui.h babelgui.hh mainwindow.h qtgui.h
FORMS += babelgui.ui mainwindow.ui
SOURCES += babelgui.cpp main.cpp mainwindow.cpp qtgui.cpp
