######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 4 17:35:49 2011
######################################################################

TEMPLATE = app
QT += network
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
